[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/joaoparracho/PyTorch-Workshop/blob/main/introduction/pytorch_basic_operations.ipynb)

In [15]:
import numpy as np
import torch

In [16]:

# scalar
print("Scalar")
x_n = 1
x_t = torch.Tensor([1])
print(x_n)
print(x_t)

# 1D Array
print("1D Array")
x_n = np.array([1.0,2.0,3.0])
x_t = np.array([1.0,2.0,3.0])
print(x_n)
print(x_t)
print(x_n.shape)
print(x_t.shape)

# 2D Array
print("2D Array")
x_n = np.array([[1.0,2.0,3.0],
                [4.0,5.0,6.0]])
x_t = torch.Tensor([[1.0,2.0,3.0],
                    [4.0,5.0,6.0]])
print(x_n)
print(x_t)
print(x_n.shape)
print(x_t.shape)

# 3D Array
print("3D Array")
x_n = np.array([[[1.0,2.0],[3.0,4.0]],
                [[5.0,6.0],[7.0,8.0]]])
x_t = torch.Tensor([[[1.0,2.0],[3.0,4.0]],
                    [[5.0,6.0],[7.0,8.0]]])

print(x_n)
print(x_t)
print(x_n.shape)
print(x_t.shape)

# 4D Array
print("4D Array")
x_n = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],
                [[[1,2],[3,4]],[[5,6],[7,8]]]])
x_t = torch.Tensor([[[[1,2],[3,4]],[[5,6],[7,8]]],
                    [[[1,2],[3,4]],[[5,6],[7,8]]]])
print(x_n)
print(x_t)
print(x_n.shape)
print(x_t.shape)

Scalar
1
tensor([1.])
1D Array
[1. 2. 3.]
[1. 2. 3.]
(3,)
(3,)
2D Array
[[1. 2. 3.]
 [4. 5. 6.]]
tensor([[1., 2., 3.],
        [4., 5., 6.]])
(2, 3)
torch.Size([2, 3])
3D Array
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
(2, 2, 2)
torch.Size([2, 2, 2])
4D Array
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
tensor([[[[1., 2.],
          [3., 4.]],

         [[5., 6.],
          [7., 8.]]],


        [[[1., 2.],
          [3., 4.]],

         [[5., 6.],
          [7., 8.]]]])
(2, 2, 2, 2)
torch.Size([2, 2, 2, 2])


### Tensor Initialisation

In [22]:

# Initialising with zeros
x = np.zeros((2,2))
y = torch.zeros((2,2))
print(x)
print(y)
# Initialising with ones
x = np.ones((2,2))
y = torch.ones((2,2))
print(x)
print(y)
# Initialising randomly
x = np.random.rand(2,2)
y = torch.rand((2,2))
print(x)
print(y)

[[0. 0.]
 [0. 0.]]
tensor([[0., 0.],
        [0., 0.]])
[[1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.]])
[[0.61739119 0.37002676]
 [0.9835852  0.65328239]]
tensor([[0.6780, 0.8082],
        [0.2837, 0.0393]])


### Tensor Attributes

In [18]:

x = torch.rand(4,3,20,20)

print(x.shape) # torch.Size([4, 3, 20, 20])
print(x.type()) # torch.FloatTensor
print(x.device) # cpu

torch.Size([4, 3, 20, 20])
torch.FloatTensor
cpu


### From numpy to PyTorch, and CUDA

In [19]:
x = np.random.rand(4,3,20,20)
# Convert numpy array to PyTorch tensor
y = torch.from_numpy(x) # Returns a cpu tensor
# Convert PyTorch tensor to numpy array
z = y.numpy()

if torch.cuda.is_available():
    device = "cuda"
else:
    device ="cpu"
# Load the tensor to the cpu or cuda (gpu)
y = y.to(device)

print(y.shape) 
print(y.type())
print(y.device)

torch.Size([4, 3, 20, 20])
torch.cuda.DoubleTensor
cuda:0


### Tensors: Operations

In [21]:

x = torch.rand((4,3,20,20))
# Indexing
x_1 = x[:,:,0:10,:] # torch.Size ([4, 3, 10, 20])
x_2 = x[:,:,10:,:] # torch.Size ([4, 3, 10, 20])
x_3 = x[:,:,:,0:10] # torch.Size ([4, 3, 20, 10])
x_4 = x[:,:,:,10:] # torch.Size ([4, 3, 20, 10])
print(x_1.shape)
print(x_2.shape)
print(x_3.shape)
print(x_4.shape)
# Concatenate tensors
y_1 = torch.cat((x_1,x_2),dim=2) # torch.Size ([4, 3, 20, 20])
y_2 = torch.cat((x_3,x_4),dim=3) # torch.Size ([4, 3, 20, 20])

print(y_1.shape)
print(y_2.shape)
# Swap tensors dimension
z = x.permute(3,0,2,1) # # torch.Size ([20, 4, 20, 3])
print(z.shape)

torch.Size([4, 3, 10, 20])
torch.Size([4, 3, 10, 20])
torch.Size([4, 3, 20, 10])
torch.Size([4, 3, 20, 10])
torch.Size([4, 3, 20, 20])
torch.Size([4, 3, 20, 20])
torch.Size([20, 4, 20, 3])
