In [7]:
import numpy as np
import torch
# scalar
print("Scalar")
x_n = 1
x_t = torch.Tensor([1])
print(x_n)
print(x_t)

# 1D Array
print("1D Array")
x_n = np.array([1.0,2.0,3.0])
x_t = np.array([1.0,2.0,3.0])
print(x_n)
print(x_t)
print(x_n.shape)
print(x_t.shape)

# 2D Array
print("2D Array")
x_n = np.array([[1.0,2.0,3.0],
                [4.0,5.0,6.0]])
x_t = torch.Tensor([[1.0,2.0,3.0],
                    [4.0,5.0,6.0]])
print(x_n)
print(x_t)
print(x_n.shape)
print(x_t.shape)

# 3D Array
print("3D Array")
x_n = np.array([[[1.0,2.0],[3.0,4.0]],
                [[5.0,6.0],[7.0,8.0]]])
x_t = np.array([[[1.0,2.0],[3.0,4.0]],
                [[5.0,6.0],[7.0,8.0]]])

print(x_n)
print(x_t)
print(x_n.shape)
print(x_t.shape)

# 4D Array
print("4D Array")
x_n = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],
                [[[1,2],[3,4]],[[5,6],[7,8]]]])
x_t = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],
                [[[1,2],[3,4]],[[5,6],[7,8]]]])
print(x_n)
print(x_t)
print(x_n.shape)
print(x_t.shape)

1
tensor([1.])
[1. 2. 3.]
[1. 2. 3.]
(3,)
(3,)
[[1. 2. 3.]
 [4. 5. 6.]]
tensor([[1., 2., 3.],
        [4., 5., 6.]])
(2, 3)
torch.Size([2, 3])
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]
(2, 2, 2)
(2, 2, 2)
